# -----------------------------------------------------
#  Copyright Iliass Mahjoub 2023.
#  Distributed under MIT License
#  (See accompanying file LICENSE
#  or copy at http://www.boost.org/LICENSE_1_0.txt)
# -----------------------------------------------------

name: STM32F446_FlashMaster
on:
  push:
    branches:
      - '**'
  pull_request:
jobs:
  target-ubuntu:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        suite: [ all ]
        gcc: ['7-2017-q4', 'latest']
    steps:
      - uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: ${{ matrix.gcc }}
      - name: update-tools
        run: sudo apt install gcc-arm-none-eabi
      - run: arm-none-eabi-gcc --version
      - name: target-ubuntu-${{ matrix.suite }}
        working-directory: ./Build/VS
        run: |
          make -f ../Make/make_stm32f446re.gmk ${{ matrix.suite }} TYP_OS=unix
          ls -la ../Bin/STM32F446_FlashMaster_x64/stm32f446re.elf ../Bin/STM32F446_FlashMaster_x64/stm32f446re.hex
